### ISSUE TITLE
CORS issue on patch 

### ISSUE THREAD

**Issue by sahinvardar** [apimda/apimda2#16]
For some reason patch methods do not return ```Access-Control-Allow-Origin``` on AWS lambda, which is required to be compliant with CORS and to be in sync with the header response from the OPTIONS request before.

**Comment by joemays** [comment]
I think we need a simple repro case here.  Assuming your referring to APIGW HTTP API w/Lambda - and it states pretty clearly [in the docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-cors.html) that this can (and for apimda2 apps probably should be) configured via APIGW, not in the app logic itself.

**Comment by sahinvardar** [comment]
I've identified the root cause of the CORS issue related to case sensitivity in HTTP methods used in fetch. The browser typically converts most HTTP methods to uppercase, as noted in the [fetch documentation](https://developer.mozilla.org/en-US/docs/Web/API/fetch#method), but not all methods are consistently handled.

> The request method, e.g., "GET", "POST". The default is "GET". Note that the [Origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) header is not set on Fetch requests with a method of [HEAD](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/HEAD) or [GET](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET). (This behavior was corrected in Firefox 65 — see [Firefox bug 1508661](https://bugzil.la/1508661).) Any string which is a case-insensitive match for one of the methods in [RFC 9110](https://www.rfc-editor.org/rfc/rfc9110#name-overview) will be uppercased automatically. If you want to use a custom method (like PATCH), you should uppercase it yourself.

Apimbda defines all supported HTTP methods in lowercase [here](https://github.com/apimda/apimda2/blob/cc02f2b35873d22fa956ce3bb7bcae7432fe44a7/packages/core/src/api.ts#L95) and uses them in the client [here](https://github.com/apimda/apimda2/blob/cc02f2b35873d22fa956ce3bb7bcae7432fe44a7/packages/client/src/client.ts#L35).

To demonstrate and verify this behavior, I set up a [test repository](https://github.com/sahinvardar/apimbda-cors-test), with a live deployment available [here](https://d13coaee4vmx6s.cloudfront.net).

To resolve this issue, we should explicitly convert HTTP methods to uppercase in the client before making requests.
